services:
  - type: web
    name: order-service-app
    env: python
    region: virginia
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: "gunicorn core.wsgi:application --workers 2"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://orderservice_yqkx_user:your-password@your-existing-db-host:5432/orderservice_yqkx"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://order-service-app.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "core.settings"
