services:
  - type: web
    name: order-service-app
    env: python
    python:
      version: "3.9.16"  
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: "gunicorn core.wsgi:application --workers 2" 
    envVars:
      - key: DATABASE_URL
        value: "postgresql://orderservice_yqkx_user:wifFmwFfNksx2xpmucL9EVGJ0O5llO7m@dpg-d00ejc7gi27c73b74k5g-a.virginia-postgres.render.com:5432/orderservice_yqkx"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://order-service-app.onrender.com"
      - key: DJANGO_SETTINGS_MODULE  
        value: "core.settings"

databases:
  - name: orderservice-db
    databaseName: orderservice_yqkx
    user: orderservice_yqkx_user
    region: virginia
    plan: free