services:
  - type: web
    name: order-service-app
    env: python
    python:
      version: "3.9.16" 
    region: virginia 
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput  # Critical for static files
<<<<<<< HEAD
    startCommand: "gunicorn wsgi:application" 
=======
    startCommand: "gunicorn customer_order_service.wsgi:application --workers 2" 
>>>>>>> 050a24509d49aa1a9d77d027732e56523c742415
    envVars:
      - key: DATABASE_URL
        value: "postgresql://orderservice_yqkx_user:wifFmwFfNksx2xpmucL9EVGJ0O5llO7m@dpg-d00ejc7gi27c73b74k5g-a.virginia-postgres.render.com:5432/orderservice_yqkx"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False" 
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://order-service-app.onrender.com"
      - key: DISABLE_COLLECTSTATIC
        value: "0"  

databases:
  - name: orderservice-db 
    databaseName: orderservice_yqkx  
    user: orderservice_yqkx_user 
    region: virginia 
    plan: free
