# Generated by Django 5.2 on 2025-05-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
